### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by Hau-Hau** [AlaricBaraou/MiraiSenseiNative#1]
Hi,

I was working on spine2d on RN too and I have stuck at same point as you at https://github.com/EsotericSoftware/spine-runtimes/issues/2360.
So, just wanted to ask whether were you able to solve this problem?

**Comment by AlaricBaraou** [comment]
Hello!

Unfortunately no I haven't.
I switched to flutter.

**Comment by Hau-Hau** [comment]
Thanks for information, hope that Flutter is working well for you !
